# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3946ac4758a64a4cfe61a5825df0b652ed68797f52f1253178dc4235483d9e0665a970809533acfcf801176fd8a47725011c5b9cb3d2a34671087f5670e09bdf

test:
  secret_key_base: bf21352e56fd5e902ba5ba307c2438d36dfe8ad5567fa3784c2d68794526840e3ef68b3795e7edbd352ff9a7a7e23dfc70d93217bf06952efa8edde5fb55a425

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
